name: '🐞 Bug Report'
description: Report a bug
title: '[BUG]: '
labels: ['bug']
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the bug
      required: true
